Repository CA22-game-creators/cookingbomb-gameserver, pull requests merged in 2021-07, with the labels that each got.

#9 DIのベース作成
  cluster-game-server/Makefile
  cluster-game-server/api/auth.go
  cluster-game-server/application/connect/input_data.go
  cluster-game-server/application/connect/input_port.go
  cluster-game-server/application/connect/interactor.go
  cluster-game-server/application/connect/output_data.go
  cluster-game-server/application/disconnect/input_data.go
  cluster-game-server/application/disconnect/input_port.go
  cluster-game-server/application/disconnect/interactor.go
  cluster-game-server/application/disconnect/output_data.go
  cluster-game-server/application/get_connection_status/input_data.go
  cluster-game-server/application/get_connection_status/input_port.go
  cluster-game-server/application/get_connection_status/interactor.go
  cluster-game-server/application/get_connection_status/output_data.go
  cluster-game-server/di/wire.go
  cluster-game-server/di/wire_gen.go
  cluster-game-server/domain/model/account/entity.go
  cluster-game-server/domain/model/account/id.go
  cluster-game-server/domain/model/account/name.go
  cluster-game-server/domain/model/account/repository.go
  cluster-game-server/domain/model/account/status.go
  cluster-game-server/errors/errors.go
  cluster-game-server/go.mod
  cluster-game-server/go.sum
  cluster-game-server/infrastructure/auth/authentication.go
  cluster-game-server/infrastructure/cache/instance.go
  cluster-game-server/infrastructure/repository/impl.go
  cluster-game-server/infrastructure/session/instance.go
  cluster-game-server/infrastructure/session/session.go
  cluster-game-server/main.go
  cluster-game-server/mock/application/connect/input_port.go
  cluster-game-server/mock/application/disconnect/input_port.go
  cluster-game-server/mock/application/get_connection_status/input_port.go
  cluster-game-server/mock/domain/model/account/repository.go
  cluster-game-server/model/account/account.go
  cluster-game-server/model/session/session.go
  cluster-game-server/presentation/connect.go
  cluster-game-server/presentation/controller.go
  cluster-game-server/presentation/disconnect.go
  cluster-game-server/presentation/game/connection.go
  cluster-game-server/presentation/game/controller.go
  cluster-game-server/presentation/game/gamedata.go
  cluster-game-server/presentation/game_data_stream.go
  cluster-game-server/presentation/get_connection_status.go
  cluster-game-server/test/infrastructure/auth/auth_token_test.go
  cluster-game-server/test/infrastructure/session/instance/new_test.go
  cluster-game-server/test/infrastructure/session/instance/operation_test.go
  cluster-game-server/test/infrastructure/session/session/operation_test.go
  cluster-game-server/test/model/account/new_from_API_responce_test.go
  cluster-game-server/test/model/session/get_status_test.go
  cluster-game-server/test/model/session/is_active_test.go
  cluster-game-server/test/presentation/connect_test.go
  cluster-game-server/test/presentation/controller_test.go
  cluster-game-server/test/presentation/game/connection/connect_test.go
  cluster-game-server/test/presentation/game/connection/disconnect_test.go
  cluster-game-server/test/presentation/game/connection/get_connection_status_test.go
  cluster-game-server/tools/tools.go
Labels: refactor, レビュー待ち

#10 Update/connection handling
  cluster-game-server/application/connect/interactor.go
  cluster-game-server/application/disconnect/interactor.go
  cluster-game-server/application/get_connection_status/interactor.go
  cluster-game-server/domain/model/account/repository.go
  cluster-game-server/domain/model/account/status.go
  cluster-game-server/errors/errors.go
  cluster-game-server/infrastructure/repository/impl.go
Labels: refactor, レビュー済

#13 ゲームストリーミング実装
  cluster-game-server/application/game_data_stream/input_data.go
  cluster-game-server/application/game_data_stream/input_port.go
  cluster-game-server/application/game_data_stream/interactor.go
  cluster-game-server/application/game_data_stream/output_port.go
  cluster-game-server/di/wire.go
  cluster-game-server/di/wire_gen.go
  cluster-game-server/docker/prod/Dockerfile
  cluster-game-server/domain/model/character/entity.go
  cluster-game-server/domain/model/character/repository.go
  cluster-game-server/go.sum
  cluster-game-server/infrastructure/repository/account/impl.go
  cluster-game-server/infrastructure/repository/character/impl.go
  cluster-game-server/mock/application/game_data_stream/input_port.go
  cluster-game-server/mock/domain/model/character/repository.go
  cluster-game-server/presentation/controller.go
  cluster-game-server/presentation/game_data_stream.go
  cluster-game-server/test/application/connect/interactor_test.go
  cluster-game-server/test/application/disconnect/interactor_test.go
  cluster-game-server/test/application/game_data_stream/interactor_test.go
  cluster-game-server/test/application/get_connection_status/interactor_test.go
  cluster-game-server/test/infrastructure/repository/character_test.go
  cluster-game-server/test/presentation/controller_test.go
  cluster-game-server/test/presentation/game_data_stream_test.go
  cluster-game-server/test/testdata/character/td.go
  cluster-game-server/test/testdata/stream/td.go
  test-client-game-server/go.mod
  test-client-game-server/go.sum
  test-client-game-server/main.go
Labels: implement, ship it!
